"""add chunk metadata

Revision ID: 89cb75f20cdc
Revises: f1ddce8e4fc2
Create Date: 2026-03-14 15:32:20.102166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89cb75f20cdc'
down_revision: Union[str, Sequence[str], None] = 'f1ddce8e4fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('metadata_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'metadata_json')
    # ### end Alembic commands ###
